# Generated by Django 6.0.2 on 2026-03-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
